AutomatedTellerMachine/AutomatedTellerMachine/Controllers/CheckingAccountController.cs
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    [Authorize]
    public class CheckingAccountController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CheckingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: CheckingAccount/Details
        public ActionResult Details()
        {
            var userId = User.Identity.GetUserId();

            var checkingAccount = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First();

            return View(checkingAccount);
        }

        [Authorize(Roles="Admin")]
        public ActionResult DetailsForAdmin(int id)
        {
            var checkingAccount = db.CheckingAccounts.Find(id);
            return View("Details", checkingAccount);
        }

        public ActionResult List()
        {
            return View(db.CheckingAccounts.ToList());
        }
        
        public ActionResult Statement(int id)
        {
            var checkingAccount = db.CheckingAccounts.Find(id);
            return View(checkingAccount.Transactions.ToList());
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // eg: /greetings/bye
        // and /greetings because of the Optional modifier,
        // but not /greetings/see-you-tomorrow because of the maxlength(3) constraint.
        [Route("greetings/{message:maxlength(3)?}")]
        public ActionResult Greet(string message)
        {
            return Content("Great: " + message);
        }

        [Route("greetings/{message?}")]
        public ActionResult GreetOther(string message)
        {
            return Content("GreatOther: " + message);
        }

        public ActionResult Serial(string letterCase)
        {
            var serial = "COURSEMVC5ATM1";
            if (letterCase == "lower")
            {
                return Content(serial.ToLower());
            }
            return Json(new { name = "serial", value = serial }, JsonRequestBehavior.AllowGet);
        }

        //Using Atribute Routing:
        //To habilitare atribute routing it is necessary go to RouteCOnfig.cs and put this code there:
        //routes.MapMvcAttributeRoutes();

        //eg. https://blogs.msdn.microsoft.com/webdev/2013/10/17/attribute-routing-in-asp-net-mvc-5/

        // eg: /reviews
        [Route("reviews")]
        public ActionResult Reviews()
        {
            return Content("Index Reviews.");
        }
        // eg: /reviews/5
        [Route("reviews/{reviewId}")]
        public ActionResult Show(int reviewId)
        {
            return Content("Selected ID: " + reviewId);
        }


        //OPTIONAL PARAMETERS:

        // eg: /reviews/5/edit/?
        //[Route("reviews/{reviewId:int}/edit/{name?}")] 
        //other way to do this:
        [Route("reviews/{reviewId:int}/edit/{name=DefaultName}")]
        public ActionResult Edit(int reviewId, string name)
        {
            if (String.IsNullOrEmpty(name))
            {
                return Content("Edit ID: " + reviewId);
            }
            return Content("Edit ID: " + reviewId + " Name: " + name);
        }

        /*
         Here, the first route will only be selected if the “id” segment of the URI is an integer. 
         Otherwise, the second route will be chosen.
         // eg: /users/5
        [Route(“users/{id:int}”]
        public ActionResult GetUserById(int id) { … }
 
        // eg: users/ken
        [Route(“users/{name}”]
        public ActionResult GetUserByName(string name) { … }
         */

        /*
         You can apply multiple constraints to a parameter, separated by a colon, for example:
        // eg: /users/5
        // but not /users/10000000000 because it is larger than int.MaxValue,
        // and not /users/0 because of the min(1) constraint.
        [Route(“users/{id:int:min(1)}”)]
        public ActionResult GetUserById(int id) { … }
         */
    }
}

AutomatedTellerMachine/AutomatedTellerMachine/Controllers/HomeController.cs
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //GET /home/index
        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccountId = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First().Id;
            ViewBag.CheckingAccountId = checkingAccountId;

            var manager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = manager.FindById(userId);
            ViewBag.Pin = user.Pin;

            return View();
        }

        //GET /home/about
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }


        public ActionResult Contact()
        {
            ViewBag.TheMessage = "Having trouble? Send us a message.";
            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            ViewBag.TheMessage = "Thanks, we got your message!" + message;
            return PartialView("_ContactThanks");
        }

        public ActionResult Foo()
        {
            ViewBag.Message = "Hello world Rossetti!";
            return View("About");
        }

        public ActionResult Serial(string letterCase)
        {
            var serial = "COURSEMVC5ATM1";
            if (letterCase == "lower")
            {
                return Content(serial.ToLower());
            }
            return Json(new { name = "serial", value = serial }, JsonRequestBehavior.AllowGet);
        }

    }
}

AutomatedTellerMachine/AutomatedTellerMachine/Controllers/TransactionController.cs
using AutomatedTellerMachine.Models;
using AutomatedTellerMachine.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private IApplicationDbContext db;

        public TransactionController()
        {
            db = new ApplicationDbContext();
        }

        public TransactionController(IApplicationDbContext dbContext)
        {
            db = dbContext;
        }

        // GET: Transaction/Deposit
        public ActionResult Deposit(int checkingAccountId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Deposit(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.SaveChanges();
                var service = new CheckingAccountService(db);
                service.UpdateBalance(transaction.CheckingAccountId);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

AutomatedTellerMachine/AutomatedTellerMachine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AutomatedTellerMachine/AutomatedTellerMachine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<div id="formSection">
    <h3>@ViewBag.TheMessage</h3>
    <form method="post" id="contactForm">
        <textarea name="message" id="message" maxlength="150" data-bind="value:message, valueUpdate:'input'"></textarea>
        <input type="submit" value="send" />
        <span data-bind="text:characteresRemaining"></span> characteres remaining
    </form>
    <img src="~/Content/Images/animated.gif" id="progress" style="display:none;" />
</div>

@section scripts{
    <script src="~/Scripts/knockout-3.4.2.js"></script>

    <script>
        function ContactViewModel() {
            var self = this;
            self.message = ko.observable('');
            self.characteresRemaining = ko.computed(function () {
                return 150 - self.message().length;
            })
        }
        ko.applyBindings(new ContactViewModel());
    </script>

    <script>
        $('#contactForm').submit(function () {
            $('#progress').show();
            $.post('', { message: $('#message').val() })
                .done(function (response) {
                    setTimeout(function () { $('#formSection').html(response); }, 2500);
                });
            return false;
        });
    </script>
}
@*
        Other way to do it:

        <div id="formSection">
        <h3>@ViewBag.TheMessage</h3>
        @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "formSection" }))
        {
            @Html.TextArea("message")
            <input type="submit" value="send" />
        }
    </div>

    @section scripts{
        @* Need this ajax to use Ajax form. To use this ajax, go to Nuget and install it *@
@* <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    }*@

AutomatedTellerMachine/AutomatedTellerMachine/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary btn-block">
            Withdrawall
        </a>
        <a href="#" class="btn btn-primary btn-block">
            Quick cash $100
        </a>
        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-primary btn-block">
            Balance Inquiry
        </a>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="@Url.Action("Statement","CheckingAccount", new { id = ViewBag.CheckingAccountId })" class="btn btn-primary btn-block">
            Print Statement
        </a>
        <a href="#" class="btn btn-primary btn-block">
            Transfer Founds
        </a>
        <a href="@Url.Action("Deposit", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId })" class="btn btn-primary btn-block">
            Deposit
        </a>
    </div>
</div>

@ViewBag.Pin


@section scripts{
    <script>var testing=true;</script>
}
@*
    You are using @Request.Browser.Browser, and that's OK! Email us at support@ros7.com if you have any problems. Or send us a tweet @@leooros7.

    @{ var amounts = new List<decimal> { 100, 22.50m, -40, 298.99m };}

    <ul>
        @foreach(decimal amount in amounts)
        {
            <li>@formatAmount(amount)</li>
        }
    </ul>

        @helper formatAmount(decimal amount)
        {
            var color = "green";
            if(amount < 0)
        {
            color = "red";
        }
        <span style="color:@color">@String.Format("{0:c}", amount)</span>
    }
*@

AutomatedTellerMachine/AutomatedTellerMachine/Views/Home/_ContactThanks.cshtml
<h3>@ViewBag.TheMessage</h3>